version: "3"
services:
  mongo:
    image: mongo:3.4.18
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - .db:/data/db
    command: mongod --smallfiles
  backend:
    image: kovacszsolt/nodejs-twitter-reader:latest
    restart: on-failure
    volumes:
      - .backend:/home/node/app/_public/
    depends_on:
      - mongo
    environment:
      PORT: "8080"
      SSR_PORT: "8081"
      WAIT_HOSTS: "mongo:27017"
      MONGOSERVER: "mongodb://mongo:27017/itcrowd"
      MONGODATABASE: "itcrowd"
      SSR_DOMAIN: "https://itcrowd.hu/"
      SSR_IMAGEPATH: "https://itcrowd.hu/image/"
      ALLOWORIGIN: "*"
      TWITTERCONSUMERKEY: "dummy"
      TWITTERCONSUMERSECRET: "dummy"
      TWITTERACCESSTOKENKEY: "14412478-dummy"
      TWITTERACCESSTOKENSECRET: "dummy"
      TWITTERSCREENNAME: "smithzsolt"
      ROOT_PATH: "/home/node/app"
      DEFAULT_IMAGE: "/twitter/image/default.jpg"
      IMAGE_STORE: "/_public/images"
      READ_COUNT: "190"
      IMAGE_SIZES: "[{\"name\": \"size1\",\"width\": 614},{\"name\": \"size2\",\"width\": 760}]"
      TWITTEREXCEPTION: "[\"1068042833796493300\",\"1057153873620725800\",\"1059328690247688200\"]"
  frontend:
    image: kovacszsolt/itcrowd-frontend-reactjs-bootstrap:latest
    restart: on-failure
    depends_on:
      - mongo
      - backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
    depends_on:
      - mongo
      - backend
      - frontend
